@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRXJ3aW4gQ29ycmFsZXMiLCJpYXQiOjE2Mjk2MTcxMzN9.LYrMrDk0r2zJj9FDLAX0dohhNlPMX-lYlOpglTaKPJI

GET http://localhost:3001/api/customers
Authorization: Bearer {{token}}

###

GET http://localhost:3001/api/customers/73122212
###

POST http://localhost:3001/api/customers 
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nit"  : 73122212,
    "name" : "Lina Corrales",
    "addr" : "Clle 41 N 14-62 2do piso",
    "phone": "00000",
    "email": "linav@hotmail.com"
}
###

PATCH http://localhost:3001/api/customers 
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nit"  : 73122212,
    "name" : "Lina Corrales Torres",
    "addr" : "Clle 41 N 14-62 2do piso",
    "phone": "00000",
    "email": "linav@hotmail.com"
}
###

POST http://localhost:3001/login 
Content-Type: application/json

{
    "username" : "Zabud",
    "password" : "1234"
}

###

DELETE http://localhost:3001/api/customers/73122212
###